### PR TITLE
1st proposal

### PR DESCRIPTION
**Pull request by lafonjm**
Quick and dirty improvements.
Many things could be done. Depends on want your wishes and expectations.
Feel free to come back to me to discuss about it.

Hope it could help ;-)

### CODE REVIEW

**Comment by glaurent** [comment]
I'm just looking for something simple that looks good in print. I implemented HTML export because a couple of users told me they were using my app to save their chats with their girlfriends, one wanted to print them, and the default output of the text view doesn't work very well.

**Comment by glaurent** [comment]
I tested it - I like the look but my main issue is that it's not compact enough. I'd rather not try to emulate the default output of Messages.app, the output should be comfortable to read in print (and preferably b&w print). If colors are used, it would be better if they reflected the ones used by the app (in which case I need to indicate the type of messages - SMS or iMessage) in the export.

**Comment by lafonjm** [comment]
OK, I will make another proposal for print purpose :-)
Thanks for all the details. 
--
Jean-Marie LAFON

Web      : http://www.lafon.mobi <http://www.lafon.mobi/>
Courriel : jean-marie@lafon.mobi <mailto:jean-marie@lafon.mobi>
Twitter  : @lafonjm

**Comment by glaurent** [comment]
Thanks a lot 👍

**Pull request merged**
